# build.ps1 — Windows one-stop build/clean script (PowerShell, mirrors Linux build.sh)
#
# Usage:
#   .\build.ps1                          # default: Release, build main only
#   .\build.ps1 -Target main             # same as above, explicit
#   .\build.ps1 -Target learn -Layer L2
#   .\build.ps1 -Target algorithms -Module ALL
#   .\build.ps1 -Target all              # main + learn(ALL) + algorithms(ALL) + notes
#   .\build.ps1 -Target notes            # build notes/image_process legacy sub-project
#   .\build.ps1 -Config Debug            # build Debug
#   .\build.ps1 -List                    # list available targets only
#
#   .\build.ps1 -Action clean                     # remove build*/ + CMake caches (keep out/, mingw-build/data)
#   .\build.ps1 -Action clean -Mode cmake         # clean CMake caches and CMakeFiles only
#   .\build.ps1 -Action clean -Mode out           # clean out/ algorithm outputs only
#   .\build.ps1 -Action clean -Mode all           # also clean out/ algorithm outputs
#   .\build.ps1 -Action clean -DryRun             # print what would be deleted, do not actually delete
#
# Conventions:
#   - Build dirs live under build/ as per-target sub-directories:
#       build/main | build/learn | build/algorithms | build/notes
#   - Uses the MinGW Makefiles generator, auto -j <core count>
#   - If mingw32-make / cmake are not in PATH, it tries common locations and hints
#
[CmdletBinding()]
param(
    [ValidateSet("build", "clean")]
    [string]$Action = "build",

    [ValidateSet("main", "learn", "algorithms", "notes", "all")]
    [string]$Target = "main",

    # learn only
    [ValidateSet("ALL", "L0", "L1", "L2", "L3", "L4", "L5")]
    [string]$Layer = "ALL",

    # algorithms only: "ALL" or semicolon-separated list, e.g. hdr;denoise_single
    [string]$Module = "ALL",

    [ValidateSet("Release", "Debug", "RelWithDebInfo")]
    [string]$Config = "Release",

    [string]$Generator = "MinGW Makefiles",
    [switch]$NoBuild    # cmake configure only, skip build
    [switch]$List       # list available Target/Layer/Module only, no build

    # clean only
    [ValidateSet("build", "all", "out", "cmake")]
    [string]$Mode = "build",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
# Support -File / dot-source / inline call: prefer $PSScriptRoot, fall back to MyInvocation
$RepoRoot = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if ($RepoRoot -and (Test-Path $RepoRoot)) {
    Set-Location $RepoRoot
    Write-Host "==> Repo root: $RepoRoot" -ForegroundColor Cyan
} else {
    Write-Warning "Could not determine repo root, skipping Set-Location (run this script from the repo root)"
}

# ============================ CLEAN ============================
if ($Action -eq "clean") {
    Write-Host "==> build.ps1 clean  Mode=$Mode  DryRun=$DryRun  Root=$RepoRoot" -ForegroundColor Cyan

    function Rm-IfExists($path, $desc, $recurse = $true) {
        if (Test-Path $path) {
            $full = (Resolve-Path $path).Path
            if ($DryRun) {
                Write-Host "[DRY] $desc`: $full" -ForegroundColor DarkYellow
            } else {
                Write-Host "[DEL] $desc`: $full" -ForegroundColor Red
                if ($recurse) {
                    Remove-Item -Recurse -Force $full -ErrorAction SilentlyContinue
                } else {
                    Remove-Item -Force $full -ErrorAction SilentlyContinue
                }
            }
        }
    }

    # CMake junk scattered at the root (generated by a direct "cmake .")
    $cmakeJunk = @(
        "CMakeCache.txt", "CMakeFiles", "CMakeScripts", "Testing",
        "Makefile", "cmake_install.cmake", "install_manifest.txt",
        "compile_commands.json", "CTestTestfile.cmake",
        "_deps", "CMakeUserPresets.json", "CMakePresets.json"
    )

    if ($Mode -eq "build" -or $Mode -eq "cmake" -or $Mode -eq "all") {
        Write-Host ""
        Write-Host "--- Cleaning build dirs (build*) ---"
        Get-ChildItem -Directory $RepoRoot -Filter "build*" | ForEach-Object {
            # Defensive guard: mingw-build holds the project's bundled OpenCV libs; never touch it.
            # Since mingw-build does not start with "build", the build* glob already skips it; this is just a redundant safety check.
            if ($_.Name -like "mingw-build") { return }
            Rm-IfExists $_.FullName "build dir"
        }
        Write-Host ""
        Write-Host "--- Cleaning CMake caches (scattered at root) ---"
        foreach ($j in $cmakeJunk) {
            Rm-IfExists (Join-Path $RepoRoot $j) "CMake junk $j"
        }
        # Standalone build dirs inside notes/image_process (obsolete leftovers, kept for backward compat)
        Rm-IfExists (Join-Path $RepoRoot "notes\image_process\build")   "notes/imgproc build"
        Rm-IfExists (Join-Path $RepoRoot "notes\image_process\build_*") "notes/imgproc build_*"
    }

    # ---- out/ cleanup ----
    if ($Mode -eq "out" -or $Mode -eq "all") {
        Write-Host ""
        Write-Host "--- Cleaning out/ algorithm outputs (keep README.md) ---"
        $outRoot = Join-Path $RepoRoot "out"
        if (Test-Path $outRoot) {
            # Everything under out/* except README.md
            Get-ChildItem -Force $outRoot -Exclude "README.md" | ForEach-Object {
                if ($_.PSIsContainer -and $_.Name -eq "algorithms") {
                    # Under algorithms/, keep README.md, remove everything else
                    Get-ChildItem -Force $_.FullName -Exclude "README.md" | ForEach-Object {
                        Rm-IfExists $_.FullName ("out/algorithms/" + $_.Name)
                    }
                } else {
                    Rm-IfExists $_.FullName ("out/" + $_.Name)
                }
            }
        }
    }

    Write-Host ""
    Write-Host "==> Clean finished ($Mode)." -ForegroundColor Green
    if ($DryRun) { Write-Host "    (DRY RUN - printed only, nothing deleted. Re-run without -DryRun to actually delete)" }
    exit 0
}

# ============================ BUILD ============================
# ---- List available targets only (weak dependency, before tool probing) ----
if ($List) {
    Write-Host ""
    Write-Host "=== Available build targets (Target) ===" -ForegroundColor Cyan
    Write-Host "  main | learn | algorithms | notes | all" -ForegroundColor White
    Write-Host ""
    Write-Host "=== learn layers (Layer) ===" -ForegroundColor Cyan
    Write-Host "  ALL | L0 | L1 | L2 | L3 | L4 | L5" -ForegroundColor White
    Write-Host ""
    Write-Host "=== algorithms modules (Module, ALL or semicolon-separated) ===" -ForegroundColor Cyan
    Write-Host "  ALL" -ForegroundColor White
    Write-Host "  denoise_single | denoise_multi | hdr | night_scene | beauty | watermark" -ForegroundColor White
    Write-Host "  edge_detection | morphology | segmentation | feature_detection | stereo" -ForegroundColor White
    Write-Host "  deblur | template_matching | inpaint | hough_transform | frequency_domain | optical_flow" -ForegroundColor White
    Write-Host ""
    Write-Host "=== Common examples ===" -ForegroundColor Cyan
    Write-Host "  .\build.ps1 -List" -ForegroundColor DarkGray
    Write-Host "  .\build.ps1 -Target algorithms -Module ALL" -ForegroundColor DarkGray
    Write-Host "  .\build.ps1 -Target algorithms -Module `"hdr;denoise_single;beauty`"" -ForegroundColor DarkGray
    Write-Host "  .\build.ps1 -Target learn -Layer L2" -ForegroundColor DarkGray
    Write-Host "  .\build.ps1 -Target all" -ForegroundColor DarkGray
    Write-Host "  .\build.ps1 -Action clean -DryRun" -ForegroundColor DarkGray
    exit 0
}

# ---- Tool probing ----
function Find-Exe($name) {
    $cmd = Get-Command $name -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    return $null
}
$cmake = Find-Exe "cmake"
$make  = Find-Exe "mingw32-make"
if (-not $cmake) { Write-Error "cmake.exe not in PATH, please install it and add to PATH"; exit 1 }
if (-not $make -and $Generator -like "*MinGW*") {
    Write-Warning "mingw32-make not in PATH; the MinGW generator may fail"
}

# ---- Assemble CMake switches per Target ----
function Invoke-CMakeBuild($buildDir, $cmakeArgs) {
    Write-Host ""
    Write-Host "==> Configure:  cmake -B $buildDir -G `"$Generator`" @cmakeArgs ..." -ForegroundColor Green
    & $cmake -B $buildDir -G $Generator @cmakeArgs
    if ($LASTEXITCODE -ne 0) { Write-Error "cmake configure failed (exit=$LASTEXITCODE)"; exit $LASTEXITCODE }

    if ($NoBuild) { Write-Host "==> -NoBuild set, skipping build"; return }
    $parallel = [Environment]::ProcessorCount
    Write-Host "==> Build:  cmake --build $buildDir -j $parallel ($Config)" -ForegroundColor Green
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    & $cmake --build $buildDir -j $parallel --config $Config
    $sw.Stop()
    if ($LASTEXITCODE -ne 0) { Write-Error "build failed (exit=$LASTEXITCODE)"; exit $LASTEXITCODE }
    Write-Host ("==> Build time: {0:F1}s (parallel={1})" -f $sw.Elapsed.TotalSeconds, $parallel) -ForegroundColor Yellow
}

$commonBase = @(
    "-DCMAKE_BUILD_TYPE=$Config"
)

# --- main ---
if ($Target -eq "main" -or $Target -eq "all") {
    $dir = "build/main"
    $args = $commonBase + @(
        "-DBUILD_MAIN=ON",
        "-DBUILD_LEARN=OFF",
        "-DBUILD_ALGORITHMS=OFF",
        "-DBUILD_NOTES=OFF"
    )
    Invoke-CMakeBuild $dir $args
    Write-Host "  -> exe: $dir\openCv.exe" -ForegroundColor Cyan
}

# --- learn ---
if ($Target -eq "learn" -or $Target -eq "all") {
    $suffix = if ($Layer -eq "ALL") { "ALL" } else { $Layer }
    $dir = "build/learn"
    $args = $commonBase + @(
        "-DBUILD_MAIN=OFF",
        "-DBUILD_LEARN=ON",
        "-DLEARN_LAYER=$Layer",
        "-DBUILD_ALGORITHMS=OFF",
        "-DBUILD_NOTES=OFF"
    )
    Invoke-CMakeBuild $dir $args
    Write-Host "  -> exes in: $dir\<stem>.exe   (each = a .cpp filename)" -ForegroundColor Cyan
}

# --- algorithms ---
if ($Target -eq "algorithms" -or $Target -eq "all") {
    $suffix = if ($Module -eq "ALL") { "ALL" } else { ($Module -replace ';', '_') }
    $dir = "build/algorithms"
    $args = $commonBase + @(
        "-DBUILD_MAIN=OFF",
        "-DBUILD_LEARN=OFF",
        "-DBUILD_ALGORITHMS=ON",
        "-DALGO_MODULE=$Module",
        "-DBUILD_NOTES=OFF"
    )
    Invoke-CMakeBuild $dir $args
    Write-Host "  -> exes in: $dir\<module>.exe   (each = <module>.cpp filename)" -ForegroundColor Cyan
    Write-Host "  -> output : out\algorithms\*.png (generated after running exe)" -ForegroundColor DarkCyan
}

# --- notes ---
if ($Target -eq "notes" -or $Target -eq "all") {
    $dir = "build/notes"
    $args = $commonBase + @(
        "-DBUILD_MAIN=OFF",
        "-DBUILD_LEARN=OFF",
        "-DBUILD_ALGORITHMS=OFF",
        "-DBUILD_NOTES=ON"
    )
    Invoke-CMakeBuild $dir $args
    Write-Host "  -> exes in: $dir\<stem>.exe   (each = a .cpp filename)" -ForegroundColor Cyan
}

Write-Host ""
Write-Host "==> Build finished successfully. Target=$Target Config=$Config" -ForegroundColor Green
Write-Host "    To run an executable, cd into the matching build/<sub>/ dir first so the relative path ../../data resolves correctly"
