# 设置当前路径
DIR_ROOT:=../../../..

DIR_LIST_SUB :=\
AddingImages


FILE_LIST_C +=\


FILE_LIST_CPP +=\



FILE_LIST_S +=\





include $(DIR_ROOT)/make_conf.mk
all:make_show make_app
clean:make_clean
include $(DIR_ROOT)/make_fun.mk

